# Generated by Django 5.0.6 on 2024-06-21 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shooter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
