# Generated by Django 5.0.6 on 2024-06-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shooter', '0002_player_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='r_g_b',
            field=models.CharField(default='255, 255, 255'),
        ),
    ]
